on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '*.md'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 15
          cache: gradle

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
        
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
        
      - name: Build with Gradle
        run: ./gradlew build

      - name: Test with Gradle
        run: ./gradlew test
